spring.application.name=sihbackend
app.matching.confidence-threshold=0.75

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sihbackend}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
